version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 634945387210.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-flask-app .

      - echo "Tagging image..."
      - docker tag my-flask-app:latest 634945387210.dkr.ecr.ap-south-1.amazonaws.com/my-flask-app:latest

  post_build:
    commands:
      - echo "Pushing image..."
      - docker push 634945387210.dkr.ecr.ap-south-1.amazonaws.com/my-flask-app:latest

      - echo "Build completed successfully"
